server:
  port: 18000

spring:
  cloud:
    gateway:
      routes:

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"  # 允许所有来源，或指定域名如 "http://example.com"
            allowed-methods: # 允许的HTTP方法
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"          # 允许所有请求头
            allow-credentials: true       # 允许携带Cookie
            max-age: 3600                 # 预检请求缓存时间（秒）

dubbo:
  application:
    name: light-api-gateway
  protocol:
    name: dubbo  # 使用 Dubbo 协议
    port: 20881  # 服务端口（若设置为 -1，则自动分配端口）
  registry:
    address: nacos://43.139.163.68:8848  # Nacos 地址
    parameters:
      namespace: public
      username: nacos
      password: oil123123