# 开发环境配置
server:
  port: 8081

springdoc:
  api-docs:
    enabled: true  # 启用OpenAPI文档生成
    path: /v3/api-docs  # 文档接口路径
  swagger-ui:
    path: /swagger-ui.html  # 原生UI路径
    tags-sorter: alpha  # 标签按字母排序
    operations-sorter: alpha  # 接口按字母排序

knife4j:
  enable: true  # 开启增强功能
  setting:
    language: zh-CN  # 中文界面
  basic:
    enable: true  # 开启Basic认证（可选）
    username: oilbone
    password: 123123

spring:
  mail:
    host: smtp.126.com
    username: oilbone@126.com
    password: GLhCjNzgzQXareYv

  rabbitmq:
    addresses: 121.43.233.234
    username: oilbone
    password: 123123123
    virtual-host: /test
    listener:
      simple:
        acknowledge-mode: auto  # 改为自动确认

  datasource:
    url: jdbc:mysql://43.139.163.68:3306/Api_project
    username: root
    password: oil123123
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    filter:
      order: -100

  web:
    verify:
      mailLimit: 60
    flow:
      period: 5
      limit: 100
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'

  data:
    redis:
      port: 6379
      host: 43.139.163.68
      database: 0
      password: oil123123