# 开发环境配置
server:
  port: 8081

springdoc:
  api-docs:
    enabled: true  # 启用OpenAPI文档生成
    path: /v3/api-docs  # 文档接口路径
  swagger-ui:
    path: /swagger-ui.html  # 原生UI路径
    tags-sorter: alpha  # 标签按字母排序
    operations-sorter: alpha  # 接口按字母排序

# /doc.html
knife4j:
  enable: true  # 开启增强功能
  setting:
    language: zh-CN  # 中文界面
  basic:
    enable: true  # 开启Basic认证（可选）
    username: oilbone
    password: 123123

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false  # 关闭驼峰转下划线

spring:

  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false

  mail:
    port: 465
    host: smtp.126.com
    username: oilbone@126.com
    password: GLhCjNzgzQXareYv
    time: 3
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true

  rabbitmq:
    addresses: 43.139.163.68
    username: oilbone
    password: oil123123
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: auto  # 改为自动确认

  datasource:
    url: jdbc:mysql://43.139.163.68:3306/Api_project
    username: root
    password: oil123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 20  # 与maximum-pool-size一致
      maximum-pool-size: 20

  security:
    filter:
      order: -100

  web:
    verify:
      mailLimit: 60
    flow:
      period: 5
      limit: 100
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'

  data:
    redis:
      port: 6379
      host: 43.139.163.68
      database: 0
      password: oil123123


dubbo:
  application:
    name: light-api-backend
  protocol:
    name: dubbo  # 使用 Dubbo 协议
    port: 20880  # 服务端口（若设置为 -1，则自动分配端口）
  registry:
    address: nacos://43.139.163.68:8848  # Nacos 地址
